Updated for style-guide and clarity reasons.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -6,25 +6,21 @@
 
 # Run unit tests
 COVERAGE=coverage
-if [ z`which coverage` = z ]
-then
-    COVERAGE=python-coverage
+if [[ -z $(which $COVERAGE) ]]; then
+  COVERAGE=python-coverage
 fi
-if $COVERAGE run --source='.' -m unittest discover --pattern='*_test.py' > /dev/null
-then
-    true
-else
-    echo "TESTS FAILED" 1>&2
-    exit 1
+if ! $COVERAGE run --source='.' -m unittest discover --pattern='*_test.py'; then
+  echo "TESTS FAILED" 1>&2
+  exit 1
 fi
 
 # Run everything through the linter
 pylint --rcfile=pylintrc --reports=n *.py > /dev/null
 # pylint return codes described here: 
 #   https://lists.logilab.org/pipermail/python-projects/2009-November/002068.html
-# We only care about fatal messages and errors
-if [ $[ $? & 3 ] -ne 0 ]
-then
+# We only care about fatal messages and errors, the existence of which are
+# assigned to bits 0 and 1 of the return code, respectively.
+if [[ $(( $? & 3 )) -ne 0 ]]; then
   echo "LINTER FAILED" 1>&2
   echo "Fix all errors and fatal messages" 1>&2
   exit 1
